### ISSUE TITLE
multiple subdomains per container

### ISSUE THREAD

**Issue by stefan-frank23** [selloween/docker-wordpress#12]
Hi,
got it to work. Except problems with the following:
```
VIRTUAL_HOST=domain1.com,www.domain1.com
VIRTUAL_PORT=8000
LETSENCRYPT_HOST=domain1.com,www.domain1.com
LETSENCRYPT_EMAIL=mail@domain1.com
```
It doesn't get certificates. HTTP works fine.

Any Ideas?

**Comment by selloween** [comment]
Have you tried testing it using only one domain? Just to make sure if the issue has to do with the subdomains or something else.

`VIRTUAL_HOST=domain1.com
VIRTUAL_PORT=8000
LETSENCRYPT_HOST=domain1.com
LETSENCRYPT_EMAIL=mail@domain1.com`

**Comment by selloween** [comment]
The syntax is correct and should work. I can't really tell without seeing the error log. The Letsencrypt container has to have access to the internet for the ACME challenge to work. If you changed your DNS records, it might take some time until they resolve correctly.
