### ISSUE TITLE
https error

### ISSUE THREAD

**Issue by jonnathanjuma** [selloween/docker-wordpress#14]
It works correctly, but with https it gives me an error, look for some things in http, how can I correct that

**Comment by pzanitti** [comment]
Mixed content (resources loaded using HTTP on an HTTPS website) used to be a warning on Chrome, now it's a stopping error. You can add these two lines at the top of `wp-config.php`, make sure to rebuild the image (`docker-compose up --build -d`):

```php
<?php
define('FORCE_SSL_ADMIN', true);
$_SERVER['HTTPS']='on';
```

**Comment by leobar37** [comment]
I would like to know why the wordpress loads but the styles do not load

**Comment by pzanitti** [comment]
> I would like to know why the wordpress loads but the styles do not load

Because of mixed content prevention in modern browsers. Read my above comment on how to make it work.

**Comment by selloween** [comment]
@pzanitti above answer is correct. closing  issue.
