### ISSUE TITLE
Warning about issue with FQDN apache 2

### ISSUE THREAD

**Issue by jimthedj65** [selloween/docker-wordpress#16]
Hi Thanks for the docker files and step by step, i am using it to set up a multi-site on my home lab and expose websites, I have carefully gone through my .env and wp-config as instructed, it seems to build out ok apart from one error which is below?

AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.80.4. Set the 'ServerName' directive globally to suppress this message

When I try to browse the website it gives me a 500 Internal Server Error
nginx/1.19.10

any guidance greatly approeciated

**Comment by selloween** [comment]
Hi,

Regarding the Apache warning, you can safely ignore it or edit the `ServerName `  to `ServerName localhost`  in `/etc/apache2/apache2.conf` 

Regarding the NGINX 500 Error - I can't say much without having the logs. You can run following command to get the log output of the container `docker logs -f nginx` (Provided the container name is nginx).
