### ISSUE TITLE
Add subdomains to SSL certificate?

### ISSUE THREAD

**Issue by bobey6** [selloween/docker-wordpress#2]
Hello,

Is it possible to add subdomains to the SSL Certificate? I know it's possible to specify additional subdomains (like www, blog, etc) when generating letsencrypt certificates from the CLI but I wasn't sure if the docker-letsencrypt-nginx-proxy-companion container supported generating them from the composer file.

Thank you!

**Comment by selloween** [comment]
Yep. Subdomains work fine.

**Comment by bobey6** [comment]
Do you know the syntax? I'd like to generate a valid certificate for both 'domain.tld' and 'www.domain.tld'. For now I'm just generating the certificate manually with certbot.

**Comment by selloween** [comment]
Sorry I checked again and I have not tried adding multiple Hosts using the Letsencrypt Proxy Companion Docker image. Regarding the NGINX Proxy, you can add multiple virtual hosts by adding them to the environment variable like this: 
```
VIRTUAL_HOST: foo.bar.com,baz.bar.com,bar.com
```
You could try the same for the `LETSENCRYPT_HOST` environment variable.
