### ISSUE TITLE
Permissions on wp-content directory

### ISSUE THREAD

**Issue by bobey6** [selloween/docker-wordpress#3]
Hello,

When trying to upload a custom theme or plugin, I noticed that the 'root' user owns the wp-content directory and Wordpress is not able to read/write. If I change the directory ownership to www-data you are able to upload files. I'm not sure if this is a bug or intentional. The fix is below:

docker exec <wordpress container> wp chown -R www-data:www-data wp-content

**Comment by selloween** [comment]
Hi! Yeah, I forgot mentioning that in the README. Thanks for bringing it up.
