### ISSUE TITLE
help

### ISSUE THREAD

**Issue by compulon** [selloween/docker-wordpress#5]
I can not make them work and I do not know what I'm doing wrong ...I want to make it work with the basics. know what exactly is optional.

**Comment by selloween** [comment]
I'm not sure what you want to achieve. Can you be more specific? If you want a really basic WordPress installation you only have to copy the `sample.env`, change the environment variables to suit your project and rename it to `.env`. Editing `wp-config.php` is purely optional depending on your project. I will close this issue as you can follow the step by step guide in the README.
