### ISSUE TITLE
it is normal?

### ISSUE THREAD

**Issue by compulon** [selloween/docker-wordpress#9]
Initializing database
cp_01 | **Deprecation warning: Your package name wordpress-docker-composer is invalid**, it should have a vendor name, a forward slash, and a package name. The vendor and package name can be words separated by -, . or _. The complete name should match "[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9]([_.-]?[a-z0-9]+)*". Make sure you fix this as Composer 2.0 will error.
cp_01 | Loading composer repositories with package information
wp_01 | WordPress not found in /var/www/html - copying now...
wp_01 | WARNING: /var/www/html is not empty! (copying anyhow)
cp_01 | Updating dependencies (including require-dev)
wp_01 | Complete! WordPress has been successfully copied to /var/www/html
wp_01 | [01-Jul-2019 08:03:05 UTC] PHP Warning:  mysqli::__construct(): (HY000/2002): Connection refused in Standard input code on line 22
wp_01 | 
wp_01 | **MySQL Connection Error: (2002) Connection refused**
.
.
.
.

**Comment by selloween** [comment]
You can ignore this warning. I removed the `name` and `description` keys  from the `composer.json` files as they are not necessary. This removes the warning and should be compatible with Composer 2.0.
